source_repository_url: https://github.com/siman-man/doc_sandbox.git
target_repository_url: https://github.com/siman-man/experiment_repo.git
source_branch: master
target_branch: master
source_lang: en
target_lang: ja
paths:
  guides/source/*.md: guides/source/ja
